# Generated by Django 4.0 on 2021-12-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
